//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Demo.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S")]
  public partial class Msg_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_C2S() {}
    
    private protocol.ProtoId _protoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"protoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.ProtoId protoId
    {
      get { return _protoId; }
      set { _protoId = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private protocol.SystemHeart _heart = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"heart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.SystemHeart heart
    {
      get { return _heart; }
      set { _heart = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C")]
  public partial class Msg_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_S2C() {}
    
    private protocol.ProtoId _protoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"protoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.ProtoId protoId
    {
      get { return _protoId; }
      set { _protoId = value; }
    }
    private protocol.ErrorCode _errorCode = protocol.ErrorCode.ERROR_TOKEN;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(protocol.ErrorCode.ERROR_TOKEN)]
    public protocol.ErrorCode errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SystemHeart")]
  public partial class SystemHeart : global::ProtoBuf.IExtensible
  {
    public SystemHeart() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SystemError_S2C")]
  public partial class SystemError_S2C : global::ProtoBuf.IExtensible
  {
    public SystemError_S2C() {}
    
    private int _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoId")]
    public enum ProtoId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM_HEART", Value=10001)]
      SYSTEM_HEART = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM_ERROR_S2C", Value=10002)]
      SYSTEM_ERROR_S2C = 10002
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_TOKEN", Value=5000)]
      ERROR_TOKEN = 5000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_PROTO_ID", Value=5001)]
      ERROR_PROTO_ID = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_SERVER", Value=5002)]
      ERROR_SERVER = 5002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_MISSING_PROTO_C2S", Value=5003)]
      ERROR_MISSING_PROTO_C2S = 5003
    }
  
}