# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Demo.proto',
  package='protocol',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nDemo.proto\x12\x08protocol\"b\n\x07Msg_C2S\x12\"\n\x07protoId\x18\x01 \x02(\x0e\x32\x11.protocol.ProtoId\x12\r\n\x05token\x18\x02 \x02(\t\x12$\n\x05heart\x18\x03 \x01(\x0b\x32\x15.protocol.SystemHeart\"U\n\x07Msg_S2C\x12\"\n\x07protoId\x18\x01 \x02(\x0e\x32\x11.protocol.ProtoId\x12&\n\terrorCode\x18\x02 \x01(\x0e\x32\x13.protocol.ErrorCode\"\r\n\x0bSystemHeart\"\x1f\n\x0fSystemError_S2C\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05*3\n\x07ProtoId\x12\x11\n\x0cSYSTEM_HEART\x10\x91N\x12\x15\n\x10SYSTEM_ERROR_S2C\x10\x92N*c\n\tErrorCode\x12\x10\n\x0b\x45RROR_TOKEN\x10\x88\'\x12\x13\n\x0e\x45RROR_PROTO_ID\x10\x89\'\x12\x11\n\x0c\x45RROR_SERVER\x10\x8a\'\x12\x1c\n\x17\x45RROR_MISSING_PROTO_C2S\x10\x8b\'')
)

_PROTOID = _descriptor.EnumDescriptor(
  name='ProtoId',
  full_name='protocol.ProtoId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_HEART', index=0, number=10001,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_ERROR_S2C', index=1, number=10002,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=259,
  serialized_end=310,
)
_sym_db.RegisterEnumDescriptor(_PROTOID)

ProtoId = enum_type_wrapper.EnumTypeWrapper(_PROTOID)
_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='protocol.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR_TOKEN', index=0, number=5000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_PROTO_ID', index=1, number=5001,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_SERVER', index=2, number=5002,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_MISSING_PROTO_C2S', index=3, number=5003,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=312,
  serialized_end=411,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
SYSTEM_HEART = 10001
SYSTEM_ERROR_S2C = 10002
ERROR_TOKEN = 5000
ERROR_PROTO_ID = 5001
ERROR_SERVER = 5002
ERROR_MISSING_PROTO_C2S = 5003



_MSG_C2S = _descriptor.Descriptor(
  name='Msg_C2S',
  full_name='protocol.Msg_C2S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protoId', full_name='protocol.Msg_C2S.protoId', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=10001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='protocol.Msg_C2S.token', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heart', full_name='protocol.Msg_C2S.heart', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=122,
)


_MSG_S2C = _descriptor.Descriptor(
  name='Msg_S2C',
  full_name='protocol.Msg_S2C',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protoId', full_name='protocol.Msg_S2C.protoId', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=10001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='protocol.Msg_S2C.errorCode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=5000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=209,
)


_SYSTEMHEART = _descriptor.Descriptor(
  name='SystemHeart',
  full_name='protocol.SystemHeart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=224,
)


_SYSTEMERROR_S2C = _descriptor.Descriptor(
  name='SystemError_S2C',
  full_name='protocol.SystemError_S2C',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protocol.SystemError_S2C.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=257,
)

_MSG_C2S.fields_by_name['protoId'].enum_type = _PROTOID
_MSG_C2S.fields_by_name['heart'].message_type = _SYSTEMHEART
_MSG_S2C.fields_by_name['protoId'].enum_type = _PROTOID
_MSG_S2C.fields_by_name['errorCode'].enum_type = _ERRORCODE
DESCRIPTOR.message_types_by_name['Msg_C2S'] = _MSG_C2S
DESCRIPTOR.message_types_by_name['Msg_S2C'] = _MSG_S2C
DESCRIPTOR.message_types_by_name['SystemHeart'] = _SYSTEMHEART
DESCRIPTOR.message_types_by_name['SystemError_S2C'] = _SYSTEMERROR_S2C
DESCRIPTOR.enum_types_by_name['ProtoId'] = _PROTOID
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg_C2S = _reflection.GeneratedProtocolMessageType('Msg_C2S', (_message.Message,), dict(
  DESCRIPTOR = _MSG_C2S,
  __module__ = 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Msg_C2S)
  ))
_sym_db.RegisterMessage(Msg_C2S)

Msg_S2C = _reflection.GeneratedProtocolMessageType('Msg_S2C', (_message.Message,), dict(
  DESCRIPTOR = _MSG_S2C,
  __module__ = 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Msg_S2C)
  ))
_sym_db.RegisterMessage(Msg_S2C)

SystemHeart = _reflection.GeneratedProtocolMessageType('SystemHeart', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMHEART,
  __module__ = 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:protocol.SystemHeart)
  ))
_sym_db.RegisterMessage(SystemHeart)

SystemError_S2C = _reflection.GeneratedProtocolMessageType('SystemError_S2C', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMERROR_S2C,
  __module__ = 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:protocol.SystemError_S2C)
  ))
_sym_db.RegisterMessage(SystemError_S2C)


# @@protoc_insertion_point(module_scope)
